### PR TITLE
Updating project metadata from Google Code to Github transition

### LINKED ISSUE #267: Update project metadata from Google Code to Github transition

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #267

### CODE REVIEW

**Comment by mro** [comment]
Hi Michael, thanks for caring.

I wonder if the urls in the poms should be permanent urls or contemporary urls. I think they should be correct in log terms. So we may better use piccolo2d.org + redirects instead of github.com urls. I mean, we already moved twice..

e.g. https://github.com/heuermh/piccolo2d.java/commit/4a520b9920e726fd17f1cec2ae62ac3aee46aca2#diff-600376dffeb79835ede4a0b285078036L52 saying `http://piccolo2d.org`

and https://github.com/heuermh/piccolo2d.java/commit/4a520b9920e726fd17f1cec2ae62ac3aee46aca2#diff-600376dffeb79835ede4a0b285078036R65 saying `http://piccolo2d.org/issues` redirecting to github.

What do you think?

**Comment by heuermh** [comment]
I would be fine with redirecting from ```http://piccolo2d.org``` for the project and issues URLs.

The ```scm``` URLs still need to point to github.com though since they are used by the Maven Release Plugin.

**Comment by mro** [comment]
ic. And github redirects are a bit strange, too. Either client-side (`<meta ...` but http://www.w3.org/QA/Tips/reback) or this here which I've never seen/used before: https://help.github.com/articles/redirects-on-github-pages/

So we may go well with non-eternal urls.

**Comment by heuermh** [comment]
Sorry, this has been sitting for so long, I'm going to merge it, and if we want to change the URLs, we can do it later in a separate commit.

**Pull request merged**
